{% set name = "rumps" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rumps-{{ version }}.tar.gz
  sha256: 17fb33c21b54b1e25db0d71d1d793dc19dc3c0b7d8c79dc6d833d0cffc8b1596

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyobjc-framework-cocoa

test:
  imports:
    - rumps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jaredks/rumps
  summary: Ridiculously Uncomplicated MacOS Python Statusbar apps.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cav71
